 workflows:
    ios-app-store:
      name: Mnemo App Store Build
      max_build_duration: 60
      environment:
        groups:
          - app-store
        xcode: latest
      scripts:
        - name: Set up signing
          script: bash sign.sh
        - name: Build IPA
          script: bash build.sh
      artifacts:
        - build/ios/ipa/*.ipa
      publishing:
        app_store_connect:
          api_key: $APP_STORE_CONNECT_PRIVATE_KEY
          key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
          issuer_id: $APP_STORE_CONNECT_ISSUER_ID
          submit_to_testflight: true
